unittec:
  iot:
    mqtt:
      client:
        enable: true
        heart: 10000  #10s
        ip: 192.168.1.22
        port: 8085
        protocol: MQTT
        ssl: false
        log: true
        option:
          user-name: admin
          password: eqwei12ewqeqw
          has-clean-session: true
          client-identifier: lajdjakhui12317689djaoqeqwe
logging:
  level:
    io.netty: debug
server:
  port: 8081
